name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          
      - name: Add GitHub Packages source
        run: dotnet nuget add source https://nuget.pkg.github.com/alifcapital/index.json --name github --username ${{ github.actor }} --password ${{ secrets.EVENTBUS_RABBITMQ_SECRET }} --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore "src/EventBus.RabbitMQ.csproj"

      - name: Build the EventBus.RabbitMQ in Debug mode
        if: github.event_name == 'pull_request'
        run: dotnet build "src/EventBus.RabbitMQ.csproj.csproj" --configuration Debug --no-restore

      - name: Build the EventBus.RabbitMQ in Release mode
        if: github.event_name != 'pull_request'
        run: dotnet build "src/EventBus.RabbitMQ.csproj.csproj" --configuration Release --no-restore